### ISSUE TITLE
__dirname undefined

### ISSUE THREAD

**Issue by stereobooster** [nathanmacinnes/injectr#21]
inside app.js

```
var application_root = __dirname;
```

Additionally `require.main` and `__filename` undefined too

**Comment by nathanmacinnes** [comment]
Hi, thanks for contributing.
This isn't actually a bug, it was a design decision. I allowed all global variables and file-specific variables in an earlier version of injectr, but decided it would be better to know exactly what my file under test was doing. Just add `__dirname` to the context file, like this:

``` javascript
injectr('../my-dir/my-app.js', {}, {
    '__dirname' : '/home/me/project/lib'
});
```

You could even give `__dirname` a getter with `Object.defineProperty`, so that you can test that your file is checking the directory correctly. I have been thinking about making this easier to do... perhaps by making it add the variables to the context only if one isn't provided:

``` javascript
// __dirname is defined
injectr('../lib/my-app.js', {});

// __dirname is not defined
injectr('../lib/my-app.js', {}, {});
```

What do you think?

**Comment by 0b10011** [comment]
Personally, I expected the node defaults to work... by default. You could always add something like this to allow for overriding:

```
...,
__dirname: mocks["__dirname"] || path.dirname(filePath),
...
```

**Comment by nathanmacinnes** [comment]
You may have noticed that I've been doing a bit more dev work on **injectr** recently. I'm going to leave this bug open because I agree it should be easier to mimic the default behaviour, whilst still allowing the maximum flexibility which the current version provides.
